- name: Deploy React to GitHub Pages
  uses: bitovi/github-actions-react-to-github-pages@v1.2.4
  with:
    checkout: true
    checkout-filter: ''
    checkout-sparse-checkout: ''
    checkout-sparse-checkout-cone-mode: true
    path: 'dist'
    install_command: 'npm ci'
    build_command: 'npm run build'
    caching: true